import { currentKospiAssessment, fundFlowEvidenceLevels, fundFlowOfficialSources, fundFlowSignals } from "@/lib/fund-flow-monitor";

export default function FundFlowPage() {
  return <main className="shell fundFlowPage">
    <header className="topbar"><a href="/" className="brandBlock"><div className="brand">KorPulse</div><div className="subtitle">Korea Industry Intelligence</div></a><nav className="nav"><a href="/global-money">Global Money</a><a href="/fund-flow" className="active">Fund Flow Monitor</a><a href="/market-events">Market Events</a><a href="/news">News & Research</a></nav></header>
    <section className="hero"><div><span className="eyebrow">FUND FLOW MONITOR</span><h1>Track market pressure without pretending to see private orders.</h1><p>KorPulse separates official observations, reproducible estimates and attributed reporting. It does not identify a hedge fund or trading motive unless a competent source has made that information public.</p></div><div className="policyCard"><strong>Publication rule</strong><span>• Evidence level on every conclusion.</span><span>• Observation window and source preserved.</span><span>• No buy, sell or price-direction instruction.</span></div></section>
    <section className="panel assessmentPanel"><div className="panelHeader"><div><span className="eyebrow">CURRENT ASSESSMENT · AS OF {currentKospiAssessment.asOf}</span><h2>{currentKospiAssessment.title}</h2></div><span className="assessmentBadge">STRONG INDICATION</span></div><p className="assessmentConclusion">{currentKospiAssessment.conclusion}</p><div className="assessmentList">{currentKospiAssessment.observations.map((item) => <article key={item.text}><span className={`evidenceLevel evidence${item.level.replaceAll(" ", "")}`}>{item.level}</span><p>{item.text}</p><a href={item.sourceUrl}>{item.sourceName} ↗</a></article>)}</div></section>
    <section className="panel" id="methodology"><div className="panelHeader"><div><span className="eyebrow">MONITORING MODEL</span><h2>Six signals, checked together</h2></div></div><div className="signalGrid">{fundFlowSignals.map((signal) => <article key={signal.name}><span>{signal.status}</span><h3>{signal.name}</h3><strong>{signal.inputs}</strong><p>{signal.purpose}</p><small>Primary source: {signal.source}</small></article>)}</div></section>
    <section className="grid2"><section className="panel" id="limitations"><span className="eyebrow">EVIDENCE LABELS</span><h2>What each label means</h2><div className="evidenceRules">{fundFlowEvidenceLevels.map((item) => <div key={item.level}><strong>{item.level}</strong><p>{item.rule}</p></div>)}</div></section><section className="panel"><span className="eyebrow">OFFICIAL STARTING POINTS</span><h2>Verify the underlying data</h2><div className="sourceShelf">{fundFlowOfficialSources.map((source) => <a href={source.url} target="_blank" rel="noreferrer" key={source.name}><small>{source.type}</small><strong>{source.name}</strong><p>{source.description}</p><span>Open official source ↗</span></a>)}</div></section></section>
  </main>;
}
