import { db } from "@/lib/db";
import { benchmarkDirectory, calculateFlowPressure, currentKospiAssessment, fundFlowEvidenceLevels, fundFlowOfficialSources, fundFlowSignals, parseFundFlowSnapshot } from "@/lib/fund-flow-monitor";

export const dynamic = "force-dynamic";

export default async function FundFlowPage() {
  const records = await db.marketImpactEvent.findMany({ where: { title: { startsWith: "FUND_FLOW_SNAPSHOT|KOSPI" }, evidenceStatus: "REGULATOR_CONFIRMED" }, orderBy: { occurredAt: "desc" }, take: 20 });
  const snapshots = records.map((record) => parseFundFlowSnapshot(record.relevanceNote)).filter((item) => item !== null);
  const latest = snapshots[0] ?? null;
  const pressure = latest ? calculateFlowPressure(latest) : null;
  return <main className="shell fundFlowPage">
    <header className="topbar"><a href="/" className="brandBlock"><div className="brand">KorPulse</div><div className="subtitle">Korea Industry Intelligence</div></a><nav className="nav"><a href="/global-money">Global Money</a><a href="/fund-flow" className="active">Fund Flow Monitor</a><a href="/market-events">Market Events</a><a href="/news">News & Research</a></nav></header>
    <section className="hero"><div><span className="eyebrow">FUND FLOW MONITOR</span><h1>Track market pressure without pretending to see private orders.</h1><p>KorPulse separates official observations, reproducible estimates and attributed reporting. It does not identify a hedge fund or trading motive unless a competent source has made that information public.</p></div><div className="policyCard"><strong>Publication rule</strong><span>• Evidence level on every conclusion.</span><span>• Observation window and source preserved.</span><span>• No buy, sell or price-direction instruction.</span></div></section>
    <section className="panel dataConnectionPanel"><div className="panelHeader"><div><span className="eyebrow">OFFICIAL DATA CONNECTION</span><h2>{latest ? `Latest verified snapshot · ${latest.observedAt.slice(0, 10)}` : "Awaiting licensed KRX data connection"}</h2></div><span className={`connectionBadge ${latest ? "connected" : "awaiting"}`}>{latest ? "CONNECTED · NOT REAL-TIME" : "NOT LIVE"}</span></div>{latest && pressure ? <><div className="flowMetricGrid"><article><span>FLOW PRESSURE</span><strong>{pressure.score ?? "—"}</strong><small>{pressure.label} · {pressure.coverage}/5 inputs</small></article><article><span>FOREIGN CASH</span><strong>{latest.foreignCashNetKrwBn ?? "—"}</strong><small>KRW bn net</small></article><article><span>PROGRAM</span><strong>{latest.programNetKrwBn ?? "—"}</strong><small>KRW bn net</small></article><article><span>VOLATILITY</span><strong>{latest.volatilityIndex ?? "—"}</strong><small>official observation</small></article></div><p className="dataTimestamp">Source: <a href={latest.sourceUrl} target="_blank" rel="noreferrer">{latest.sourceName} ↗</a> · Retrieved {latest.retrievedAt.slice(0, 10)} · This is a dated snapshot, not a live trading feed.</p></>:<div className="connectionEmpty"><p>KRX requires registered OPEN API access. KorPulse will not scrape the public website or display fabricated live figures. Until approved data is connected, the monitor publishes methodology, official links and evidence-rated assessments only.</p><a href="https://data.krx.co.kr/" target="_blank" rel="noreferrer">Open KRX Data Marketplace ↗</a></div>}</section>
    <section className="panel benchmarkPanel"><div className="panelHeader"><div><span className="eyebrow">GLOBAL INDEX COMPARISON</span><h2>KOSPI versus major U.S. equity indices</h2></div><span className="comparisonBasis">RETURN-BASED · LOCAL CURRENCY</span></div><p className="comparisonNote">Index levels are not directly comparable. KorPulse compares percentage returns over matching 1-day, 5-trading-day and 20-trading-day windows. Dates remain visible because Korea and U.S. sessions close at different times and observe different holidays.</p>{latest?.benchmarks?.length ? <div className="benchmarkTable"><div className="benchmarkHead"><strong>INDEX</strong><strong>AS OF</strong><strong>1D</strong><strong>5D</strong><strong>20D</strong><strong>SOURCE</strong></div>{latest.benchmarks.map((item) => <div className="benchmarkRow" key={item.code}><div><small>{item.region}</small><strong>{item.name}</strong></div><span>{item.asOf.slice(0, 10)}</span>{[item.return1dPct, item.return5dPct, item.return20dPct].map((value, index) => <span className={value == null ? "" : value > 0 ? "positiveReturn" : value < 0 ? "negativeReturn" : ""} key={index}>{value == null ? "—" : `${value > 0 ? "+" : ""}${value.toFixed(2)}%`}</span>)}<a href={item.sourceUrl} target="_blank" rel="noreferrer">{item.sourceName} ↗</a></div>)}</div>:<div className="benchmarkDirectory">{benchmarkDirectory.map((item) => <a href={item.sourceUrl} target="_blank" rel="noreferrer" key={item.code}><small>{item.region} · OFFICIAL SERIES</small><strong>{item.name}</strong><span>Awaiting aligned observations ↗</span></a>)}</div>}<div className="comparisonLimits"><strong>Interpretation boundary</strong><span>Same-direction declines suggest a global component.</span><span>KOSPI underperformance alongside foreign and futures selling suggests an additional Korea-specific flow component.</span><span>This comparison does not identify a fund or prove causation.</span></div></section>
    <section className="panel assessmentPanel"><div className="panelHeader"><div><span className="eyebrow">CURRENT ASSESSMENT · AS OF {currentKospiAssessment.asOf}</span><h2>{currentKospiAssessment.title}</h2></div><span className="assessmentBadge">STRONG INDICATION</span></div><p className="assessmentConclusion">{currentKospiAssessment.conclusion}</p><div className="assessmentList">{currentKospiAssessment.observations.map((item) => <article key={item.text}><span className={`evidenceLevel evidence${item.level.replaceAll(" ", "")}`}>{item.level}</span><p>{item.text}</p><a href={item.sourceUrl}>{item.sourceName} ↗</a></article>)}</div></section>
    <section className="panel" id="methodology"><div className="panelHeader"><div><span className="eyebrow">MONITORING MODEL</span><h2>Six signals, checked together</h2></div></div><div className="signalGrid">{fundFlowSignals.map((signal) => <article key={signal.name}><span>{signal.status}</span><h3>{signal.name}</h3><strong>{signal.inputs}</strong><p>{signal.purpose}</p><small>Primary source: {signal.source}</small></article>)}</div></section>
    <section className="grid2"><section className="panel" id="limitations"><span className="eyebrow">EVIDENCE LABELS</span><h2>What each label means</h2><div className="evidenceRules">{fundFlowEvidenceLevels.map((item) => <div key={item.level}><strong>{item.level}</strong><p>{item.rule}</p></div>)}</div></section><section className="panel"><span className="eyebrow">OFFICIAL STARTING POINTS</span><h2>Verify the underlying data</h2><div className="sourceShelf">{fundFlowOfficialSources.map((source) => <a href={source.url} target="_blank" rel="noreferrer" key={source.name}><small>{source.type}</small><strong>{source.name}</strong><p>{source.description}</p><span>Open official source ↗</span></a>)}</div></section></section>
  </main>;
}
