export type IndustryCompanyEvidence = {
  industrySlug: string;
  stageSlug: string;
  companyNameKo: string;
  companyNameEn: string;
  evidenceLabel: "COMPANY_CONFIRMED";
  sourceTitle: string;
  sourceUrl: string;
  sourceLanguage: "en" | "ko";
  checkedAt: string;
  productFamilies: readonly string[];
  publicationNote: string;
};

export const industryCompanyEvidence: readonly IndustryCompanyEvidence[] = [
  {
    industrySlug: "food-manufacturing",
    stageSlug: "ingredients",
    companyNameKo: "CJ제일제당",
    companyNameEn: "CJ CheilJedang",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "CJ FNT official launch and ingredient portfolio",
    sourceUrl: "https://www.cj.co.kr/en/newsroom/pressreleases/news-detail/1564",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Fermented seasoning blends", "Flavour ingredients", "Amino acids for human nutrition"],
    publicationNote: "The product relationship is attributed to CJ CheilJedang's own publication. It is not an independent market-rank or performance finding.",
  },
  {
    industrySlug: "food-manufacturing",
    stageSlug: "ingredients",
    companyNameKo: "삼양사",
    companyNameEn: "Samyang Corporation",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "Samyang Corporation — Food Ingredients",
    sourceUrl: "https://www.samyangcorp.com/en/food-business/food-ingredients",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Sugar", "Starch and starch sweeteners", "Wheat flour and premix", "Oils and fats"],
    publicationNote: "The categories reproduce the company's official business description; production scale and market position are not inferred.",
  },
  {
    industrySlug: "food-manufacturing",
    stageSlug: "ingredients",
    companyNameKo: "대상",
    companyNameEn: "Daesang Corporation",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "Daesang Ingredient — Anhydrous crystalline glucose",
    sourceUrl: "https://ingredient.daesang.com/s/channelproduct/a0W5i000000GWU3EAO/%EB%AC%B4%EC%88%98%EA%B2%B0%EC%A0%95%ED%8F%AC%EB%8F%84%EB%8B%B9?language=ko",
    sourceLanguage: "ko",
    checkedAt: "2026-08-17",
    productFamilies: ["Anhydrous crystalline glucose"],
    publicationNote: "Product properties and certifications remain company-published information unless separately confirmed by the named certifying body.",
  },
  {
    industrySlug: "chemicals",
    stageSlug: "polymers",
    companyNameKo: "LG화학",
    companyNameEn: "LG Chem",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "LG Chem — Petrochemicals product list",
    sourceUrl: "https://www.lgchem.com/product/petrochemicals",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["ABS", "ASA", "PVC", "Synthetic rubber", "Superabsorbent polymer"],
    publicationNote: "Only product categories shown in LG Chem's official catalogue are mapped. Comparative quality and market-rank language is not republished as fact.",
  },
  {
    industrySlug: "chemicals",
    stageSlug: "basic-chemicals",
    companyNameKo: "롯데케미칼",
    companyNameEn: "LOTTE Chemical",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "LOTTE Chemical — Basic Petrochemicals",
    sourceUrl: "https://product.lottechem.com/en/basic_materials/tl.do",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Benzene", "Toluene", "Mixed xylene", "Para-xylene", "Butadiene", "Styrene monomer"],
    publicationNote: "The record reflects the company's official product catalogue. Production volume, competitiveness and downstream customer relationships are not inferred.",
  },
  {
    industrySlug: "chemicals",
    stageSlug: "polymers",
    companyNameKo: "롯데케미칼",
    companyNameEn: "LOTTE Chemical",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "LOTTE Chemical — Polymer products",
    sourceUrl: "https://product.lottechem.com/en/basic_materials/injection.do",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Polyethylene", "Polypropylene", "PET"],
    publicationNote: "Only named polymer families are mapped. Performance descriptions and market-position language remain attributed to the company and are not independently endorsed.",
  },
  {
    industrySlug: "refining",
    stageSlug: "refining",
    companyNameKo: "GS칼텍스",
    companyNameEn: "GS Caltex",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "GS Caltex — Petroleum business",
    sourceUrl: "https://www.gscaltex.com/en/business/oilrefinary",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Crude-oil refining", "Kerosene and diesel desulfurisation", "Heavy-oil upgrading"],
    publicationNote: "The process relationship is company-attributed. Capacity, rank and quality claims are not republished without a separately dated comparable source.",
  },
  {
    industrySlug: "refining",
    stageSlug: "fuel-products",
    companyNameKo: "GS칼텍스",
    companyNameEn: "GS Caltex",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "GS Caltex — Petroleum products",
    sourceUrl: "https://www.gscaltex.com/en/Business/OilRefinary/etc",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Gasoline", "Diesel", "Kerosene", "LPG", "Jet fuel", "Marine fuel oil", "Asphalt"],
    publicationNote: "Only products named by the company's official catalogue are mapped. Product quality and comparative claims are not independently endorsed.",
  },
  {
    industrySlug: "refining",
    stageSlug: "export-and-distribution",
    companyNameKo: "GS칼텍스",
    companyNameEn: "GS Caltex",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "GS Caltex — Petroleum supply and export",
    sourceUrl: "https://www.gscaltex.com/en/business/oilrefinary",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Domestic petroleum supply", "Service-station distribution", "Petroleum-product exports"],
    publicationNote: "This records channels described by the company. Station counts, export ratios and destination counts are excluded because they require date-specific verification.",
  },
  {
    industrySlug: "refining",
    stageSlug: "refining",
    companyNameKo: "S-OIL",
    companyNameEn: "S-OIL",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "S-OIL — Oil refining overview and facilities",
    sourceUrl: "https://www.s-oil.com/en/energy/OilRefining.aspx",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Crude-oil refining", "Light-oil desulfurisation", "Gasoline production", "Residue upgrading"],
    publicationNote: "The operating processes are attributed to S-OIL. Capacity and leadership claims are not carried into the portal without an independently comparable dataset.",
  },
  {
    industrySlug: "refining",
    stageSlug: "petrochemical-feedstocks",
    companyNameKo: "S-OIL",
    companyNameEn: "S-OIL",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "S-OIL — RUC and ODC",
    sourceUrl: "https://www.s-oil.com/en/m/energy/RUCODC.aspx",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Propylene", "Propylene oxide", "Polypropylene"],
    publicationNote: "The product and process links follow the company's project description. Investment size, profitability and import-substitution claims are not republished as verified outcomes.",
  },
  {
    industrySlug: "steel",
    stageSlug: "steelmaking",
    companyNameKo: "현대제철",
    companyNameEn: "Hyundai Steel",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "Hyundai Steel — Integrated and electric-arc steelmaking process",
    sourceUrl: "https://www.hyundai-steel.com/en/product-tech/rebar",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Blast-furnace and converter route", "Electric-arc-furnace route", "Continuous casting", "Slabs, blooms and billets"],
    publicationNote: "The process map follows Hyundai Steel's official explanation. Production volumes, environmental superiority and comparative efficiency are not inferred.",
  },
  {
    industrySlug: "steel",
    stageSlug: "rolling",
    companyNameKo: "현대제철",
    companyNameEn: "Hyundai Steel",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "Hyundai Steel — Hot-rolled steel",
    sourceUrl: "https://www.hyundai-steel.com/en/product-tech/hot-rolled",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Hot-rolled coil", "Structural hot-rolled steel", "Pipe steel", "Automotive hot-rolled steel", "High-carbon and alloy steel"],
    publicationNote: "Only official product categories and stated application classes are mapped. Capacity, quality and delivery-performance claims are excluded.",
  },
  {
    industrySlug: "steel",
    stageSlug: "rolling",
    companyNameKo: "현대제철",
    companyNameEn: "Hyundai Steel",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "Hyundai Steel — Cold-rolled steel",
    sourceUrl: "https://www.hyundai-steel.com/en/product-tech/cold-rolled",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Cold-rolled coil", "Galvanized coil", "Galvannealed coil", "Electro-galvanized coil", "Aluminium-silicon coated coil"],
    publicationNote: "Product names are taken from the company's catalogue. Global ranking, annual capacity and performance-superiority language are not republished.",
  },
  {
    industrySlug: "steel",
    stageSlug: "mobility-and-infrastructure",
    companyNameKo: "현대제철",
    companyNameEn: "Hyundai Steel",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "Hyundai Steel — Steel plate",
    sourceUrl: "https://www.hyundai-steel.com/en/product-tech/plate",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Shipbuilding plate", "Offshore-structure plate", "Offshore-wind plate", "Pipeline and pressure-vessel plate"],
    publicationNote: "Applications are company-attributed catalogue categories. Suitability for a specific project or customer is not implied.",
  },
  {
    industrySlug: "steel",
    stageSlug: "mobility-and-infrastructure",
    companyNameKo: "현대제철",
    companyNameEn: "Hyundai Steel",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "Hyundai Steel — Mobility parts",
    sourceUrl: "https://www.hyundai-steel.com/en/product-tech/mobility-parts",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Hot-stamped parts", "Tailor-welded blanks", "Hydroformed parts", "Metal bipolar plates"],
    publicationNote: "The manufacturing categories follow the company's official page. Fuel-efficiency, safety and emissions outcomes are not treated as independently proven.",
  },
  {
    industrySlug: "biohealth",
    stageSlug: "manufacturing",
    companyNameKo: "셀트리온",
    companyNameEn: "Celltrion",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "Celltrion — Biopharmaceutical production facilities",
    sourceUrl: "https://celltrion.com/en-us/business/production/facilities",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Biologic drug substance manufacturing", "Biologic drug product manufacturing", "Contract manufacturing"],
    publicationNote: "This records company-described manufacturing roles and sites. Capacity, production success, regulatory certification and quality claims require separate current confirmation.",
  },
  {
    industrySlug: "biohealth",
    stageSlug: "quality-and-regulation",
    companyNameKo: "셀트리온",
    companyNameEn: "Celltrion",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "Celltrion — Business overview",
    sourceUrl: "https://www.celltrion.com/en-us/business/overview",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Biopharmaceutical quality control", "GMP-oriented production management"],
    publicationNote: "Quality-system descriptions remain company-attributed. This card does not confirm a product approval, inspection result, efficacy, safety or current GMP status.",
  },
  {
    industrySlug: "biohealth",
    stageSlug: "global-distribution",
    companyNameKo: "셀트리온",
    companyNameEn: "Celltrion",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "Celltrion — Business overview and distribution",
    sourceUrl: "https://www.celltrion.com/en-us/business/overview",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Direct biopharmaceutical distribution network", "Overseas product supply"],
    publicationNote: "The distribution role is based on the company's own description. Country counts, market leadership and product authorization status are not independently confirmed here.",
  },
  {
    industrySlug: "biohealth",
    stageSlug: "research",
    companyNameKo: "SK바이오사이언스",
    companyNameEn: "SK bioscience",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "SK bioscience — Company overview",
    sourceUrl: "https://www.skbioscience.com/en/bioscience/about_04",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Vaccine research and development", "Vaccine co-development", "Vaccine manufacturing infrastructure"],
    publicationNote: "Only the company's stated research and manufacturing roles are mapped. First-in-market, approval, safety and effectiveness claims are not republished.",
  },
  {
    industrySlug: "biohealth",
    stageSlug: "manufacturing",
    companyNameKo: "SK바이오사이언스",
    companyNameEn: "SK bioscience",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "SK bioscience — Domestic business",
    sourceUrl: "https://www.skbioscience.com/en/business/domestic_01",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Vaccine manufacturing", "Consignment production", "Outsourced production coordination"],
    publicationNote: "Manufacturing relationships shown on the official page remain company-attributed and date-specific. Product approval and clinical status must be checked with the relevant regulator.",
  },
  {
    industrySlug: "machinery",
    stageSlug: "machine-tools",
    companyNameKo: "현대위아",
    companyNameEn: "HYUNDAI WIA",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "HYUNDAI WIA — Machine tool business",
    sourceUrl: "https://en.hyundai-wia.com/",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Machine tools", "Machine-tool design and production", "Machine-tool after-sales service"],
    publicationNote: "The business scope follows the company website. Precision, productivity, global leadership and complete-automation claims are not independently endorsed.",
  },
  {
    industrySlug: "machinery",
    stageSlug: "factory-automation",
    companyNameKo: "현대위아",
    companyNameEn: "HYUNDAI WIA",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "HYUNDAI WIA — Smart factory and automation",
    sourceUrl: "https://en.hyundai-wia.com/",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Smart-factory solutions", "Factory automation", "Autonomous and guided mobile robots"],
    publicationNote: "Only business categories publicly named by the company are mapped. No installation, customer or performance relationship is inferred.",
  },
  {
    industrySlug: "machinery",
    stageSlug: "factory-automation",
    companyNameKo: "두산로보틱스",
    companyNameEn: "Doosan Robotics",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "Doosan Robotics — Collaborative robot products and solutions",
    sourceUrl: "https://www.doosanrobotics.com/en/",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Collaborative robots", "Palletising", "Machine tending", "Assembly automation", "Robot training"],
    publicationNote: "Product families and applications follow the official catalogue. Market rank, client logos, safety superiority and productivity outcomes are not republished as verified facts.",
  },
  {
    industrySlug: "machinery",
    stageSlug: "factory-automation",
    companyNameKo: "LS ELECTRIC",
    companyNameEn: "LS ELECTRIC",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "LS ELECTRIC — Smart Automation Solution",
    sourceUrl: "https://www.ls-electric.com/ko/product/main/automation",
    sourceLanguage: "ko",
    checkedAt: "2026-08-17",
    productFamilies: ["Programmable logic controllers", "AC drives", "Servo systems", "Human-machine interfaces", "Smart-factory IT solutions"],
    publicationNote: "The record translates named product categories from the Korean official page. Operational-efficiency outcomes and customer-specific performance are not assumed.",
  },
  {
    industrySlug: "machinery",
    stageSlug: "production-equipment",
    companyNameKo: "한화세미텍",
    companyNameEn: "Hanwha Semitech",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "Hanwha Semitech — Product catalogue",
    sourceUrl: "https://www.hanwhasemitech.com/en/",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Chip mounters and SMT equipment", "Die and flip-chip bonders", "Hybrid bonders", "PE-CVD and ALD equipment", "CNC Swiss lathes"],
    publicationNote: "Only product classes displayed by the company are mapped. World's-first, domestic-rank, yield, defect-rate and productivity claims are excluded.",
  },
  {
    industrySlug: "defense-aerospace",
    stageSlug: "components",
    companyNameKo: "한국항공우주산업",
    companyNameEn: "Korea Aerospace Industries (KAI)",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "KAI — Commercial aerostructures",
    sourceUrl: "https://www.koreaaero.com/EN/Business/AerostructuresCommercial_Boeing.aspx",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Commercial-aircraft wing structures", "Commercial aerostructures"],
    publicationNote: "Only the publicly named aerostructure role is mapped. Contract scope, delivery status, production volume, technical tolerance and non-public customer terms are excluded.",
  },
  {
    industrySlug: "defense-aerospace",
    stageSlug: "systems-integration",
    companyNameKo: "한국항공우주산업",
    companyNameEn: "Korea Aerospace Industries (KAI)",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "KAI — Public business categories",
    sourceUrl: "https://www.koreaaero.com/EN/Default.aspx",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Fixed-wing aircraft", "Rotary-wing aircraft", "Uncrewed aerial vehicles", "Training systems", "Satellites and launch-vehicle assembly"],
    publicationNote: "This is a high-level public business map only. Performance, armament, operational use, vulnerabilities, deployment and security-sensitive specifications are excluded.",
  },
  {
    industrySlug: "defense-aerospace",
    stageSlug: "research-and-development",
    companyNameKo: "한국항공우주산업",
    companyNameEn: "Korea Aerospace Industries (KAI)",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "KAI — Aerospace and space business overview",
    sourceUrl: "https://www.koreaaero.com/EN/",
    sourceLanguage: "en",
    checkedAt: "2026-08-17",
    productFamilies: ["Aircraft development", "Satellite development participation", "Civil aerospace engineering"],
    publicationNote: "Only disclosed development fields are listed. Programme maturity, government acceptance, readiness and future capability statements are not treated as verified outcomes.",
  },
  {
    industrySlug: "defense-aerospace",
    stageSlug: "components",
    companyNameKo: "한화에어로스페이스",
    companyNameEn: "Hanwha Aerospace",
    evidenceLabel: "COMPANY_CONFIRMED",
    sourceTitle: "Hanwha Aerospace — Public overseas locations and operations",
    sourceUrl: "https://m.hanwhaaerospace.com/eng/whoweare/location/overseas.do",
    sourceLanguage: "ko",
    checkedAt: "2026-08-17",
    productFamilies: ["Civil-aircraft engine components", "Aircraft-engine component manufacturing"],
    publicationNote: "The role is limited to the activity publicly stated for named company locations. Engine specifications, defence applications, production volumes and customer programmes are excluded.",
  },
];

export function getIndustryCompanyEvidence(industrySlug: string, stageSlug: string) {
  return industryCompanyEvidence.filter((record) => record.industrySlug === industrySlug && record.stageSlug === stageSlug);
}
